[package]
name = "sc2"
version = "0.1.0"
authors = ["Damien Stanton <damien.stanton@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
bytes = "0.4"
prost = "0.4"
prost-derive = "0.4"

[build-dependencies]
prost-build = "0.4"
